version: '3'
services:
  goodwe_modbus:
    image: thgau/goodwe_modbus:latest
    restart: unless-stopped
    ports: 
      - ${GOODWE_MODBUS_PORT:-8899}:8899
    environment:
      - GOODWE_IP=${GOODWE_IP}

  evcc:
    command:
      - evcc
    container_name: evcc
    image: evcc/evcc:latest
    ports:
      - 7070:7070/tcp
      - 8887:8887/tcp
      - 7090:7090/udp
      - 9522:9522/udp
    volumes:
      - $PWD/evcc.yaml:/etc/evcc.yaml
      - $PWD/.evcc:/root/.evcc
    restart: unless-stopped
